spring:
  application:
    name: exchange-rate-chal

  exchangerate:
    base-url: http://api.exchangerate.host
    access-key: ${EXCHANGERATE_ACCESS_KEY:80350e608951d20e11379447dd7fc403}

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60s

  graphql:
    graphiql:
      enabled: true

springdoc:
  swagger-ui:
    tags-sorter: alpha

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: caches, health, info

jwt:
  secret: ${JWT_BASE64_SECRET:c2VjcmV0LWRldmVsb3BtZW50LWtleS1uZWVkcy10by1iZS1sb25nZXI=}
  expiration-ms: 300000

rate-limit:
  capacity: 5
  refill-tokens: 1
  refill-ms: 10000